### PR TITLE
Add sim://const

### PR DESCRIPTION
**Pull request by ddequidt**
Add const to SimPVFactory

### CODE REVIEW

**Comment by kasemir** [comment]
If you want a constant value, you can already use `loc://xxx(10)` to get a local variable that starts out with value 10. Or `=10` to use a formula, which can also be written as `eq://10`.

The `=10` or `="Some Constant Text"` notation is consistent with what BOY used.
So I don't see a need to add a new `sim://const` notation.

**Comment by kasemir** [comment]
Meant to say: Instead of adding a new sim://const, should import the equation support from phoebus.

**Comment by kasemir** [comment]
Updated the PV support from phoebus, so now `=3.14` or `="Some Text"` are supported as constant formulas.

Does that solve you need for constant PVs?

**Comment by ddequidt** [comment]
> Updated the PV support from phoebus, so now `=3.14` or `="Some Text"` are supported as constant formulas.
> 
> Does that solve you need for constant PVs?

It's just than I still have OPIs with sim://const.
So if we use webdisplay we will migrate then.

No need to add more code.

**Comment by kasemir** [comment]
Can you send some examples for sim://const PVs that you use?
I assume they're mostly numeric? Maybe some strings? Enum? Arrays?
If we add sim://const, I'd like to do that in both the phoebus desktop and the display builder web runtime.

**Comment by ddequidt** [comment]
> Can you send some examples for sim://const PVs that you use?
> I assume they're mostly numeric? Maybe some strings? Enum? Arrays?
> If we add sim://const, I'd like to do that in both the phoebus desktop and the display builder web runtime.

I've just found numeric and strings.
sim://const(0)
sim://const(1)
sim://const(3.14)
sim://const("###")
...

**Comment by kasemir** [comment]
OK, provided an implementation that handles those example PVs and will also support `sim://const("A", "B", "C", "D")` or `sim://const(1, 2, 3, 4)` for arrays.

**Pull request closed without merging**
